
import {Inter} from "next/font/google"
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/toaster";



  

const inter = Inter({subsets: ["latin"] });

export const metadata = {
  title: "DeepHire",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
    return (
      <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <Toaster className="z-50"/>
          {children}</body>
      </html>
      </ClerkProvider>
    );
  }