/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*import React, { useEffect, useRef, useState } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";

export function Avatar(props)  {
  const { nodes, materials } = useGLTF("/models/67833e7073e27d4bcb78a343.glb");

  // Load animations
  const { animations: idleAnimations } = useFBX("/movements/Breathing Idle.fbx");
  const { animations: talk1Animations } = useFBX("/movements/Talking(3).fbx");
  const { animations: talk2Animations } = useFBX("/movements/Talking(4).fbx");
  const { animations: talk3Animations } = useFBX("/movements/Talking(5).fbx");
  const { animations: talk4Animations } = useFBX("/movements/Talking(6).fbx");
  const { animations: talk5Animations } = useFBX("/movements/Talking(7).fbx");
  const { animations: meet1Animations } = useFBX("/movements/meeting.fbx");


  // Assign custom names to animations
  idleAnimations[0].name = "idle";
  talk1Animations[0].name = "talk1";
  talk2Animations[0].name = "talk2";
  talk3Animations[0].name = "talk3";
  talk4Animations[0].name = "talk4";
  talk5Animations[0].name = "talk5";
  meet1Animations[0].name="meet1";

  // Combine animations
  const animations = [
    idleAnimations[0],
    talk1Animations[0],
    talk2Animations[0],
    talk3Animations[0],
    talk4Animations[0],
    talk5Animations[0],
    meet1Animations[0]
  ];

  const [currentAnimation, setCurrentAnimation] = useState("idle");
  const group = useRef();
  const { actions } = useAnimations(animations, group);

  // Animation effect
  useEffect(() => {
    const action = actions[currentAnimation];
    if (action) {
      action.reset?.().fadeIn?.(0.5).play();
    }
    return () => action?.fadeOut?.(0.5);
  }, [currentAnimation, actions]);
  
  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  )
}


useGLTF.preload('/models/animations.glb')
useGLTF.preload("/models/67833e7073e27d4bcb78a343.glb");
useFBX.preload("/movements/Breathing Idle.fbx");
useFBX.preload("/movements/Talking(3).fbx");
useFBX.preload("/movements/Talking(4).fbx");
useFBX.preload("/movements/Talking(5).fbx");
useFBX.preload("/movements/Talking(6).fbx");
useFBX.preload("/movements/Talking(7).fbx");*/




