// // // // /*
// // // // Auto-generated by: https://github.com/pmndrs/gltfjsx
// // // // */



import React, { useEffect, useRef, useState } from "react";
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import * as THREE from "three";


 function Avatar2(props) {
  const { animation: initialAnimation, position, isSpeaking } = props;
  const group = useRef();
  const [animationsLoaded, setAnimationsLoaded] = useState(false);
  
  const { nodes, materials } = useGLTF('/models/ladymorph.glb');
  
  const { animations: idleAnims } = useFBX("/ladymovements/ladyidle.fbx");
  const { animations: sit1Anims } = useFBX("/ladymovements/Sitting Idle.fbx");
  const { animations: sit2Anims } = useFBX("/ladymovements/Sitting Talking.fbx");

  const { animations: talk10Anims } = useFBX("/ladymovements/Talking(10).fbx");
  const { animations: talk11Anims } = useFBX("/ladymovements/Talking(11).fbx");
  const { animations: talk9Anims } = useFBX("/ladymovements/Talking(9).fbx");
  const { animations: greetAnims } = useFBX("/ladymovements/Standing Greeting.fbx");
  
  // Rename animations for clarity.
  idleAnims[0].name = "idle";
  sit1Anims[0].name="sitidle";
  sit2Anims[0].name="sittalk";
  talk10Anims[0].name = "talk10";
  talk11Anims[0].name = "talk11";
  talk9Anims[0].name = "talk9";
  greetAnims[0].name = "greet";
  
  const allAnimations = [idleAnims[0], talk10Anims[0], talk9Anims[0], greetAnims[0],talk11Anims[0],sit2Anims[0],sit1Anims[0]];
  // useAnimations returns both actions and the mixer.
  const { actions, mixer } = useAnimations(allAnimations, group);


  
  // Local state for Leva-controlled animation and facial expression.
  const [localAnimation, setLocalAnimation] = useState(initialAnimation || "idle");
  const [localFacialExpression, setLocalFacialExpression] = useState("default"); 

  const { animationControl, facialExpressionControl, randomAnimationWhileSpeaking } = useControls({
    animationControl: {
      value: localAnimation,
      options: ["idle", "talk10", "talk9", "greet","talk11","sitidle","sittalk"],
      label: "Animation",
    },
    
    randomAnimationWhileSpeaking: {
      value: false,
      label: "Random Animation while Speaking",
    },
  });

  useEffect(() => {
    setLocalAnimation(animationControl);
  }, [animationControl]);

  
  useEffect(() => {
    let randomAnimInterval;
    if (isSpeaking && randomAnimationWhileSpeaking) {
      const speakingAnims = ["talk10", "talk9"]; 
      randomAnimInterval = setInterval(() => {
        const randomAnim = speakingAnims[Math.floor(Math.random() * speakingAnims.length)];
        setLocalAnimation(randomAnim);
      }, 2000); // switch every 2 seconds (adjust as needed)
    }
    return () => {
      if (randomAnimInterval) clearInterval(randomAnimInterval);
    };
  }, [isSpeaking, randomAnimationWhileSpeaking]);

  useEffect(() => {
    if (!isSpeaking) {
      setLocalAnimation("idle");
    }
  }, [isSpeaking]);

  useEffect(() => {
    if (!actions || Object.keys(actions).length === 0) return;
    if (!animationsLoaded) {
      setAnimationsLoaded(true);
    }
    const currentAction = actions[localAnimation];
    const previous = group.current.userData.prevAnimation || localAnimation;
    const previousAction = actions[previous];
    // Use mixer stats to compute fade duration.
    const fadeDuration = mixer.stats.actions.inUse === 0 ? 0 : 0.5;
    if (!previousAction || previousAction === currentAction) {
      currentAction.reset().fadeIn(fadeDuration).play();
    } else {
      previousAction.fadeOut(fadeDuration);
      currentAction.reset().fadeIn(fadeDuration).play();
    }
    group.current.userData.prevAnimation = localAnimation;
  }, [localAnimation, actions, animationsLoaded, mixer]);

  useFrame(() => {
    const armBone = group.current.getObjectByName("LeftArm");
    if (armBone) {
      armBone.rotation.y += .4; // tilt arm up slightly
    }
  });
  // Blink Logic.
  useEffect(() => {
    if (!nodes.Wolf3D_Head?.morphTargetDictionary) return;
    const blinkLeftIndex =
      nodes.Wolf3D_Head.morphTargetDictionary["eyeBlinkLeft"] !== undefined
        ? nodes.Wolf3D_Head.morphTargetDictionary["eyeBlinkLeft"]
        : nodes.Wolf3D_Head.morphTargetDictionary["eyeClosed"] !== undefined
        ? nodes.Wolf3D_Head.morphTargetDictionary["eyeClosed"]
        : -1;
    const blinkRightIndex =
      nodes.Wolf3D_Head.morphTargetDictionary["eyeBlinkRight"] !== undefined
        ? nodes.Wolf3D_Head.morphTargetDictionary["eyeBlinkRight"]
        : blinkLeftIndex;
    const blinkInterval = setInterval(() => {
      if (blinkLeftIndex !== -1) {
        nodes.Wolf3D_Head.morphTargetInfluences[blinkLeftIndex] = 1;
      }
      if (blinkRightIndex !== -1) {
        nodes.Wolf3D_Head.morphTargetInfluences[blinkRightIndex] = 1;
      }
      setTimeout(() => {
        if (blinkLeftIndex !== -1) {
          nodes.Wolf3D_Head.morphTargetInfluences[blinkLeftIndex] = 0;
        }
        if (blinkRightIndex !== -1) {
          nodes.Wolf3D_Head.morphTargetInfluences[blinkRightIndex] = 0;
        }
      }, 150);
    }, 2000);
    return () => clearInterval(blinkInterval);
  }, [nodes.Wolf3D_Head]);

  // Head Tracking.
  useFrame((state) => {
    if (group.current && group.current.getObjectByName("Head")) {
      group.current.getObjectByName("Head").lookAt(state.camera.position);
    }
  });

  useEffect(() => {
    let toggleInterval;
    if (
      isSpeaking &&
      nodes &&
      nodes.Wolf3D_Head?.morphTargetDictionary &&
      nodes.Wolf3D_Teeth?.morphTargetDictionary
    ) {
      toggleInterval = setInterval(() => {
        const randomU = Math.random() < 0.5 ? 0 : 1;
        const randomE = Math.random() < 0.5 ? 0 : 1;
        const randomPP = Math.random() < 0.5 ? 0 : 1;
        const randomSS = Math.random() < 0.5 ? 0 : 1;

        nodes.Wolf3D_Head.morphTargetInfluences[
          nodes.Wolf3D_Head.morphTargetDictionary["viseme_U"]
        ] = randomU;
        nodes.Wolf3D_Head.morphTargetInfluences[
          nodes.Wolf3D_Head.morphTargetDictionary["viseme_PP"]
        ] = randomPP;
        nodes.Wolf3D_Head.morphTargetInfluences[
          nodes.Wolf3D_Head.morphTargetDictionary["viseme_SS"]
        ] = randomSS;
        nodes.Wolf3D_Teeth.morphTargetInfluences[
          nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_E"]
        ] = randomE;
      }, 160);
    } else {
        nodes.Wolf3D_Head.morphTargetInfluences[
          nodes.Wolf3D_Head.morphTargetDictionary["viseme_U"]
        ] = 0;
        nodes.Wolf3D_Head.morphTargetInfluences[
          nodes.Wolf3D_Head.morphTargetDictionary["viseme_PP"]
        ] = 0;
        nodes.Wolf3D_Head.morphTargetInfluences[
          nodes.Wolf3D_Head.morphTargetDictionary["viseme_SS"]
        ] = 0;
        nodes.Wolf3D_Teeth.morphTargetInfluences[
          nodes.Wolf3D_Teeth.morphTargetDictionary["viseme_E"]
        ] = 0;
      }
    
    return () => {
      if (toggleInterval) clearInterval(toggleInterval);
    };
  }, [isSpeaking, nodes]);

  

  const morphControls = useControls("MorphTargets", () => {
    const dict = nodes?.Wolf3D_Head?.morphTargetDictionary || {};
    return Object.assign(
      {},
      ...Object.keys(dict).map((key) => ({
        [key]: {
          label: key,
          value: nodes?.Wolf3D_Head?.morphTargetInfluences[dict[key]] || 0,
          min: 0,
          max: 1,
          step: 0.01,
          onChange: (val) => {
            if (nodes && nodes.Wolf3D_Head) {
              nodes.Wolf3D_Head.morphTargetInfluences[dict[key]] = val;
            }
          },
        },
      }))
    );
  });

  return (
    <group position={position} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
    </group>
  );
}

useGLTF.preload("/models/64f1a714fe61576b46f27ca2.glb");
useFBX.preload("/ladymovements/ladyidle.fbx");
useFBX.preload("/ladymovements/Talking(10).fbx");
useFBX.preload("/ladymovements/Talking(11).fbx");
useFBX.preload("/ladymovements/Talking(9).fbx");
useFBX.preload("/ladymovements/Standing Greeting.fbx");

export default Avatar2;

